export const videoList = [
  {
    id: 0,
    vide_thumbnail:
      'https://i.ytimg.com/vi/iMzXPmWtMAw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCnbbT5egMZULcRNz2kui67S8-mYQ',
    video_time: '8:47',
    video_title: 'Islam Makhachev`s 7-fight Win Streak',
    video_views: '14 mln wyświetleń',
    video_uploadtime: '1 rok temu',
    channel_avatar:
      'https://yt3.ggpht.com/NncdOpHt-t7QaZBIGIYqDz-6qv6j-_Gf3ilCnaRWiOSLLCOl7FOBz0q9lliRhYj6YwpAW_BEL8Y=s68-c-k-c0x00ffffff-no-rj',
    channel_name: 'UFC - Ultimate Fighting Championship',
  },
  {
    id: 1,
    vide_thumbnail:
      'https://i.ytimg.com/vi/ZyKSZVJje48/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBkUj3aX_AnVI6cuHWJAtt0QprINg',
    video_time: '2:59',
    video_title: 'Josef Bratan x Alberto - ZŁOMEK prod. Swizzy/Syru',
    video_views: '945 tyś wyświetleń',
    video_uploadtime: '2 miesiące temu',
    channel_avatar:
      'https://yt3.ggpht.com/PxobmBkKf22DYLOJAbepI-Xlwla-fNVJS0As6e18q02uNXS0gIRRxtyFCp_aTn8dVkxh2oNc0A=s48-c-k-c0x00ffffff-no-rj',
    channel_name: 'miejskajungla.team🌍',
  },
  {
    id: 2,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 3,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 4,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 5,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 6,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 7,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 8,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 9,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 10,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 11,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 12,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 13,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 14,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
  {
    id: 15,
    vide_thumbnail: '',
    video_time: '',
    video_title: '',
    video_views: '',
    video_uploadtime: '',
    channel_avatar: '',
    channel_name: '',
  },
];
